### ISSUE TITLE
Please do not steal assets from the original CandyCraft

### ISSUE THREAD

**Issue by Jonathing** [Bread-NiceCat/CandyCraftCE#1]
Hi, I'm Jonathan. I'm one of the executives at Cryptic Mushroom. Despite the events of the past few days, you need to understand that *we* still hold the original mod, and whether or not we give the *official* mod to someone else is our decision. If you wish to develop a CandyCraft-inspired mod or a "CandyCraft Unofficial" mod, that is ok.

However, what is *not* ok is stealing assets from the original mod. Looking through the assets directory in this mod, it is clear that a good number of textures have been ripped directly from the mod. While the original mod's repository is licensed under GPLv3, that is specifically for the code only. **The assets remain unlicensed and are not for you to use.** Please refrain from using our assets, the original mod's name unmodified (i.e. not appending the word "Unofficial" or not using your own unique name), or our team's name on your mod. We do not endorse unofficial ports of our mods, even if they have been dormant for a long time. We still hold the rights to them unless we have relinquished them back to their original owner (which is not the case for CandyCraft).

On an unrelated note, I have taken severe issue with how you have conducted yourself with the development of this mod. You began development of this mod in secret from us, then ask us well into development if we would like to give you the original mod itself. That was easily the fastest way for us to lose our trust in you. The excuses you listed in your original inquiry to Cipher Zero X do not excuse that, when you could've come forth and asked us yourself if you would've liked to have the mod or have joined our team. We do not work well with this kind of behavior, and we have no intentions of giving the original mod to someone who acts in this manner.

And no, re-coloring textures does not instantly make them different from the original textures. Please use your own, original textures if you plan on using the same items from the original CandyCraft in your unofficially-inspired mod.

**Comment by Bread-NiceCat** [comment]
I don't know what you mean. The textures have been almost all repainted.

**Comment by Bread-NiceCat** [comment]
And the reason I use GPLv3 is just my preference, it has nothing to do with the original Licence, because the code is written entirely by myself, and I don't use any line of code from the original mod.

**Comment by Bread-NiceCat** [comment]
I wanted to join the mushroom team, but zero rudely rejected me and put me on the blacklist

**Comment by BreadNiceCat** [comment]
不想和你这种人说话,block了

**Comment by Jonathing** [comment]
> And the reason I use GPLv3 is just my preference, it has nothing to do with the original Licence, because the code is written entirely by myself, and I don't use any line of code from the original mod.

I do not care about your code, I simply care about the assets. My point is that merely changing the colors of some of the textures (what you call re-painting) is not enough for them to be different enough from the original mod. A good example is the bow: the have the exact same pixels and textures, but merely have slightly different color palettes. I would strongly prefer that you have a unique bow textured, even if it ends up looking somewhat similar.

I ran a PowerShell script across this repositority and the original repository, and the following textures have exact SHA matches with the originals. Please eventually either remove them or have them retextured.

![Matched Textures](https://cdn.moddinglegacy.com/891442027241490137-WindowsTerminal_yLSpWudVMM.png)

> I wanted to join the mushroom team, but zero rudely rejected me and put me on the blacklist

Cipher Zero X rudely rejected you from joining our team because the way you have conducted yourself thus far (as I have stated in the issue's original body) does not suit well with our team and our team members. You made the conscious decision to develop this mod in secret without asking us for the mod in the first place or to join our team. That is not the correct way to go about things.

I do not wish to argue this any further. Please just take my words to heart and don't steal assets and make sure that this mod stays listed as unofficial or change the name.

**Comment by Bread-NiceCat** [comment]
Please give me a way to contact the original creator. I'd like to talk to him (or her) alone.
![IVNWG9Z7W(FE@YG}{XRR12](https://github.com/BreadNiceCat/CandyCraft/assets/121159360/c70774b8-253f-4b4e-8f9b-1b6f9a7575bd)

**Comment by Bread-NiceCat** [comment]
I dont want to bb with you, It's 1:00am, I'll go sleeping!

**Comment by 0Starocean0** [comment]
> > And the reason I use GPLv3 is just my preference, it has nothing to do with the original Licence, because the code is written entirely by myself, and I don't use any line of code from the original mod.
> 
> I do not care about your code, I simply care about the assets. My point is that merely changing the colors of some of the textures (what you call re-painting) is not enough for them to be different enough from the original mod. A good example is the bow: the have the exact same pixels and textures, but merely have slightly different color palettes. I would strongly prefer that you have a unique bow textured, even if it ends up looking somewhat similar.
> 
> I ran a PowerShell script across this repositority and the original repository, and the following textures have exact SHA matches with the originals. Please eventually either remove them or have them retextured.
> 
> ![Matched Textures](https://camo.githubusercontent.com/1c5a6f41543ab494224a80e0e0409767a4967223bc0527db24b99781bb216fdb/68747470733a2f2f63646e2e6d6f6464696e676c65676163792e636f6d2f3839313434323032373234313439303133372d57696e646f77735465726d696e616c5f794c5370577564564d4d2e706e67)
> 
> > I wanted to join the mushroom team, but zero rudely rejected me and put me on the blacklist
> 
> Cipher Zero X rudely rejected you from joining our team because the way you have conducted yourself thus far (as I have stated in the issue's original body) does not suit well with our team and our team members. You made the conscious decision to develop this mod in secret without asking us for the mod in the first place or to join our team. That is not the correct way to go about things.
> 
> I do not wish to argue this any further. Please just take my words to heart and don't steal assets and make sure that this mod stays listed as unofficial or change the name.

@Jonathing 
Good, I made mostly new textures and I'll keep doing this. I want to say sth about it.
First, aren't ur bow recolored from Vanilla? Did Mojang agreed This? If Mojang agreed u, it's great because I recolored from vanilla bow and not yours.
(Bruh 'yours', how ironic. As I know, all textures are made by valentin4311.)
I'll keep making new textures. I'll keep doing this. U wanna our assets be different as 'yours' old stuff. Great. I have to remind you that if you don't make new textures, no one will play what you call the 'official version' in this day and age.
Why don't u just finish The Midnight at first? Everybody wanna see u update and release it. But u wanna revive CC that u already abandoned.
